---
title: "PS270 Final Project"
author: "Samantha Dombar"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---

```{r}
install.packages("distill", repos = "https://cloud.r-project.org")
library(distill)
```


## Project thoughts

I am interested in exploring data related to social media and deomocracy, whether that be advertising statistics or social media and self identification.


## Data Set & Research Question

The research question I will be answering using regression analysis is: To what extent does exposure to negative advertisements in U.S. Congressional primary elections influence a voter’s likelihood of voting against the candidate featured in the ad? I will use data from the Federal Election Commission as well as advertising tone data from a study by the Wesleyan Research Project to help answer this question. Specifically, Wesleyan created a data set which codes political advertisements as positive, contrast, or negative in U.S. Congressional races. I plan to draw on negativity bias and it's impact on political persuasion. I hypothesize that low or medium levels of exposure to negative advertisements will increase a voter's likelihood of voting against the featured candidate. However, I think high levels of exposure may cause voter's to be less likely to vote against the candidate, as they may feel pitied toward the candidate continuously backlashes, or be upset with the other candidates for campaigning crueley.

The independent variable is the proportion of total advertisements in a congressional primary race that are coded as negative, measured at the district-election level using Wesleyan Media Project data; this variable varies across races and election cycles. The dependent variable is vote choice (or vote share against the targeted candidate), measured either as individual-level survey responses (1 = voted against the candidate, 0 = otherwise) or district-level vote share from official election returns compiled by the FEC. A positive and statistically significant relationship between the proportion of negative ads and vote share against the targeted candidate would support my hypothesis. Yet, a statistically significant negative relationship would disprove my hypothesis by suggesting that negative ads either have no effect or potentially backfire.

## Set-up code

Do not have access to the data yet-in the process of getting it from Wesleyan researchers.


